blog/urls.py
from django.conf.urls import url
from . import views
from django.urls import path
app_name='blog'

urlpatterns = [
    path('',views.post_list,name='post_list'),
    path('tags/<tag_slug>/',views.post_list,name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<post>/',views.post_detail,name='post_detail'),
    path('<post_id>/share/',views.post_share,name='post_share')
]
  

mysite/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'blog/',include(('blog.urls','blog'),namespace='blog')),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User 
from django.urls import reverse
from taggit.managers import TaggableManager 


# Create your models here.
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,self).get_queryset().filter(status='published')
class Post(models.Model):
    STATUS_CHOICES=(
        ('draft','Draft'),
        ('published','published')
    )
    title=models.CharField(max_length=250)
    slug=models.SlugField(max_length=250,unique_for_date='publish')
    author=models.ForeignKey(User,related_name='blog_posts',on_delete=models.CASCADE)
    body=models.TextField()
    publish=models.DateTimeField(default=timezone.now)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    status=models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft')
    objects=models.Manager()
    published=PublishedManager()
    tags=TaggableManager()

    class Meta:
        ordering=('-publish',)
    
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,
                                                self.publish.strftime('%m'),
                                                self.publish.strftime('%d'),
                                                self.slug
                                    ])
class Comment(models.Model):
    post=models.ForeignKey(Post,related_name='comments',on_delete=models.CASCADE)
    name=models.CharField(max_length=80)
    email=models.EmailField()
    body=models.TextField()
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    active=models.BooleanField(default=True)

    class Meta:
        ordering=('created',)

    def __str__(self):
        return 'comment by {} on {}'.format(self.name,self.post)

blog/forms.py
from django import forms
from blog.models import Comment


class EmailPostForm(forms.Form):
    name=forms.CharField(max_length=25)
    email=forms.EmailField()
    to=forms.EmailField()
    comments=forms.CharField(required=False,widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=('name','email','body')
        

blog/views.py
from django.shortcuts import render,get_object_or_404
from blog.models import Post,Comment
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from blog.forms import EmailPostForm,CommentForm
from django.core.mail import message, send_mail
from taggit.models import Tag
from django.db.models import Count


def post_list(request,tag_slug=None):
    object_list=Post.published.all()
    tag=None
    if tag_slug:
        tag=get_object_or_404(Tag,slug=tag_slug)
        object_list=object_list.filter(tags__in=[tag])
    # retrieve max of 3 pages
    paginator=Paginator(object_list,3)
    page=request.GET.get('page')
    try:
        posts=paginator.page(page)
    except PageNotAnInteger:
        posts=paginator.page(1)
    except EmptyPage:
        posts=paginator.page(paginator.num_pages)
    return render(request,'blog/post/list.html',{'posts':posts,'tag':tag})

def post_detail(request,year,month,day,post):
    post=get_object_or_404(Post,slug=post,
                                status='published',
                                publish__year=year,
                                publish__month=month,
                                publish__day=day
        )
    comments=post.comments.filter(active=True)
    if request.method == 'POST':
        comment_form=CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment=comment_form.save(commit=False)
            new_comment.post=post
            new_comment.save()
    else:
        comment_form=CommentForm()
    
    post_tags_id=post.tags.values_list('id',flat=True)
    similar_posts=Post.published.filter(tags__in=post_tags_id).exclude(id=post.id)
    similar_posts=similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]
    return render(request,'blog/post/detail.html',{'post':post,
                                                    'comments':comments,
                                                    'comment_form':comment_form,
                                                    'similar_posts':similar_posts
                                                })

def post_share(request,post_id):
    post=get_object_or_404(Post,id=post_id,status='published')
    sent=False
    if request.method == 'POST':
        form=EmailPostForm(request.POST)
        if form.is_valid():
            # adictionary of form fields with their values
            cd=form.cleaned_data
            post_url=request.build_absolute_uri(post.get_absolute_url())
            subject='{} ({}) recommended you reading "{}"'.format(cd['name'],cd['email'],post.title)
            message='read "{}" at {}\n\n {}\'s comments: {}'.format(post.title,post_url,cd['name'],cd['comments'])
            # don't spam me(only contact)
            send_mail(subject,message,'myblog@mysite.com',[cd['to']])
            sent=True
    else:
        form=EmailPostForm()
    return render(request,'blog/post/share.html',{'post':post,
                                                    'form':form,
                                                    'sent':sent
                                                        })

blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title> {% block title %}{% endblock title %} </title>
        <link href=" {% static 'css/blog.css' %}" rel="stylesheet">
    </head>
    <body>
        <div id="content">
            {% block content %}{% endblock content %}
        </div>
        
        <div>
            <h2>
                My blog
            </h2>
            <p>this is my blog. i've written {% total_posts %} posts so far.</p>
            {% show_latest_posts 3 %}
        </div>

    </body>
    </html>

blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% block title %}My Blog{% endblock title %}
{% block content %}
    <h1>My Blog</h1>
   
    <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
    <p class="date">Published {{ post.publish }} by {{ post.author}}</p>
    {{ post.body|safe|markdown }}
    <p><a href="{% url 'blog:post_share' post.id %}">share this post</a><p>
    <h2>Similar posts</h2>
    {% for post in similar_posts in  %}
        <p><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></p>
    {% empty %}
        there are no similar posts yet.
    {% endfor %}
    {% with comments.count as total_comments %}
        <h2>{{ total_comments }} comment{{ total_comments|pluralize }}</h2>
    {% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">Comment {{ forloop.counter }} by {{ comment.name }} {{ comment.created }}</p>
            {{ comment.body|linebreaks }}
        </div>
        {% empty %}
        <p>there are no comments yet.</p>
    {% endfor %}

    {% if new_comment %}
        <p> your comment has been added.</p>
    {% else %}
        <h2>add a new comment</h2>
        <form action="." method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="add comment"></p>
        </form>
    {% endif %}
{% endblock content %}

 

blog/templates/blog/post/latest_posts.html
<ul>
    {% for latest_post in latest_posts %}
        <li><a href="{{ post.get_absolute_url }}">{{ latest_post.title }}</a></li>
    {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% block title %}My Blog{% endblock title %}
{% block content %}
    <h1>My Blog</h1>
    {% if tag %}
        <h2>posts tagged with "{{ tag.name }}"</h2>
    {% endif %}
    {% for post in posts %}
        <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
        <p class="tags">
            Tags: 
            {% for tag in post.tags.all %}
                <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
                {% if not forloop.last %},{% endif %}
            {% endfor %}
        </p>
        <p class="date">Published {{ post.publish }} by {{ post.author}}</p>
        {{ post.body|safe|markdown|truncatewords_html:30 }}
    {% endfor %}
    {% include "pagination.html" with page=posts %}
{% endblock content %}

blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}
{% block title %}share a post{% endblock title %}
{% block content %}
    {% if sent %}
        <h2>email sent successfully</h2>
        <p>{{ post.title }} was sent successfully by email.</p>
        {% else %}
            <h1>share {{ post.title }} by email</h1>
            <form action="." method="post">
                {{ form.as_p }}
                {% csrf_token %}
                <input type="submit" value="send e-mail">
            </form>
    {% endif %}
{% endblock content %}

blog/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">next</a>
        {% endif %}
    </span>

</div>